#spring:
#  redis:
#    host: 192.168.164.130
#    port: 6379
#    password: 123456
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 500
#        min-idle: 0
#    lettuce:
#      shutdown-timeout: 0
spring:
  redis:
    host: 192.168.164.131
    port: 6379
    password: haohaoxue123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 10
