server:
    port: 8222
spring:
    application:
        name: CLOUD-GATEWAY
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
        gateway:
            discovery:
                locator:
                    enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
            routes:
                  - id: payment_routh   #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
                    uri: lb://service-edu   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错uri: http://localhost:8001         #匹配后提供服务的路由地址
                    predicates:
                       - Path=/eduservice/**          #断言，路径相匹配的进行路由

                  - id: service-ucenter #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
                    uri: lb://service-ucenter   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
                    predicates:
                        - Path=/educenter/**          #断言，路径相匹配的进行路由
#
                  - id: service-ucenter #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
                    uri: lb://service-ucenter   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
                    predicates:
                        - Path=/educenter/**          #断言，路径相匹配的进行路由
#
                  - id: service-order #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
                    uri: lb://service-order   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
                    predicates:
                      - Path=/eduOrder/**          #断言，路径相匹配的进行路由

                  - id: service-vod #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
                    uri: lb://service-vod   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
                    predicates:
                      - Path=/eduvod/**          #断言，路径相匹配的进行路由

                  - id: eduoss #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
                    uri: lb://eduoss   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
                    predicates:
                      - Path=/service-oss/**          #断言，路径相匹配的进行路由

                  - id: service-statistics #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
                    uri: lb://service-statistics   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
                    predicates:
                      - Path=/edusta/**          #断言，路径相匹配的进行路由

                  - id: service-acl #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
                    uri: lb://service-acl   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
                    predicates:
                      - Path=/*/acl/**          #断言，路径相匹配的进行路由







